# Generated by Django 5.0.1 on 2024-01-16 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_distance', models.FloatField()),
                ('distance_base_price', models.FloatField()),
                ('distance_additional_price', models.FloatField()),
                ('time_base_multiplier', models.FloatField()),
                ('wait_time', models.FloatField()),
            ],
        ),
    ]
